In [5]:
import jax.numpy as jnp
import time
from jax import jacobian

### (b)

In [2]:
def f(x):
    return 1/2 * (jnp.dot(x,x) + jnp.dot(a,x) ** 2)
def df(x):
    return x + jnp.dot(jnp.dot(a,x),a)
def df2(x):
    return jnp.eye(x.shape[0]) + jnp.outer(a,a)

In [9]:
df_jax = jacobian(f) 
df2_jax = jacobian(df_jax) 

### (c)

In [3]:
x = jnp.array([1,2,3,4,5,6,7,8,9,10]).astype(float)
a = jnp.array([1]* 10).astype(float)
f(x),df(x),df2(x)

(DeviceArray(1705., dtype=float32),
 DeviceArray([56., 57., 58., 59., 60., 61., 62., 63., 64., 65.], dtype=float32),
 DeviceArray([[2., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
              [1., 2., 1., 1., 1., 1., 1., 1., 1., 1.],
              [1., 1., 2., 1., 1., 1., 1., 1., 1., 1.],
              [1., 1., 1., 2., 1., 1., 1., 1., 1., 1.],
              [1., 1., 1., 1., 2., 1., 1., 1., 1., 1.],
              [1., 1., 1., 1., 1., 2., 1., 1., 1., 1.],
              [1., 1., 1., 1., 1., 1., 2., 1., 1., 1.],
              [1., 1., 1., 1., 1., 1., 1., 2., 1., 1.],
              [1., 1., 1., 1., 1., 1., 1., 1., 2., 1.],
              [1., 1., 1., 1., 1., 1., 1., 1., 1., 2.]], dtype=float32))

In [7]:
df_jax(x)

DeviceArray([56., 57., 58., 59., 60., 61., 62., 63., 64., 65.], dtype=float32)

In [8]:
df2_jax(x)

DeviceArray([[2., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
             [1., 2., 1., 1., 1., 1., 1., 1., 1., 1.],
             [1., 1., 2., 1., 1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 2., 1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 2., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 2., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1., 2., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1., 1., 2., 1., 1.],
             [1., 1., 1., 1., 1., 1., 1., 1., 2., 1.],
             [1., 1., 1., 1., 1., 1., 1., 1., 1., 2.]], dtype=float32)

In [19]:
def run_test(func,x,n=100):
    start = time.time()
    for _ in range(n):
        func(x)
    end = time.time()
    print(func.__name__,', time:',end - start,', n:',n)

For n=100:

In [20]:
run_test(df,x)
run_test(df_jax,x)
run_test(df2,x)
run_test(df2_jax,x)

df , time: 0.006024837493896484 , n: 100
jacfun , time: 0.593843936920166 , n: 100
df2 , time: 0.03345608711242676 , n: 100
jacfun , time: 1.7416160106658936 , n: 100


For n=1000:

In [21]:
run_test(df,x,n=1000)
run_test(df_jax,x,n=1000)
run_test(df2,x,n=1000)
run_test(df2_jax,x,n=1000)

df , time: 0.03178691864013672 , n: 1000
jacfun , time: 5.52968692779541 , n: 1000
df2 , time: 0.3766179084777832 , n: 1000
jacfun , time: 13.732815027236938 , n: 1000


In [23]:
import numpy as np

In [78]:
B = np.round(np.random.uniform(1,2,[n,n]))
B = B / np.linalg.norm(B)
C = np.ones([n,n])

In [108]:
v = np.ones(n)

In [96]:
n = 10
C = np.ones([n,n])
A = C + (n-2) * np.eye(n)
B = C - np.eye(n)

In [112]:
np.dot(v,np.dot(B,v)) / np.dot(v,v)

9.0

In [105]:
np.linalg.eig(A)[1],np.linalg.eig(B)[1]

(array([[-0.9486833 ,  0.31622777, -0.49692935,  0.07219191, -0.16384702,
         -0.15849326, -0.05496722,  0.09047309, -0.05496722,  0.09047309],
        [ 0.10540926,  0.31622777,  0.85833251, -0.00802132,  0.25806104,
          0.23143563,  0.20311211, -0.04498958,  0.20311211, -0.04498958],
        [ 0.10540926,  0.31622777, -0.0451754 , -0.40775077,  0.41633972,
          0.71721799,  0.11046741,  0.09960502,  0.11046741,  0.09960502],
        [ 0.10540926,  0.31622777, -0.0451754 , -0.48930074, -0.17527292,
         -0.28650286,  0.15246932,  0.17764967,  0.15246932,  0.17764967],
        [ 0.10540926,  0.31622777, -0.0451754 ,  0.26443633,  0.64015747,
         -0.54165233,  0.0107265 ,  0.08002852,  0.0107265 ,  0.08002852],
        [ 0.10540926,  0.31622777, -0.0451754 , -0.48930074,  0.09113148,
          0.16547472, -0.46471415, -0.46472417, -0.46471415, -0.46472417],
        [ 0.10540926,  0.31622777, -0.0451754 ,  0.26443633, -0.26664244,
         -0.03186997,  0.7372281