In [102]:
import jax.numpy as jnp
import time
from jax import grad,vmap,jit,hessian

In [98]:
def f(x):
    return 1/2 * (jnp.dot(x,x) + jnp.dot(a,x) ** 2)
def df(x):
    return 1/2 * (2 * x + 2 * jnp.dot(jnp.dot(a,x),a))
def df2(x):
    return 1/2 * (2 * jnp.eye(x.shape[0]) + 2 * jnp.outer(a,a))

In [99]:
x = jnp.array([1,2,3]).astype(float)
a = jnp.array([1,2,3]).astype(float)
f(x),df(x),df2(x)

(DeviceArray(105., dtype=float32),
 DeviceArray([15., 30., 45.], dtype=float32),
 DeviceArray([[ 2.,  2.,  3.],
              [ 2.,  5.,  6.],
              [ 3.,  6., 10.]], dtype=float32))

In [119]:
df_jax = jacobian(f) 
df2_jax = jacobian(df_jax) 

In [123]:
df_jax(x)

DeviceArray([15., 30., 45.], dtype=float32)

In [122]:
df2_jax(x)

DeviceArray([[ 2.,  2.,  3.],
             [ 2.,  5.,  6.],
             [ 3.,  6., 10.]], dtype=float32)

In [130]:
def run_test(func,x,n=100):
    start = time.time()
    func(x)
    end = time.time()
    print(func.__name__,', time:',end - start,', n:',n)

In [131]:
run_test(df,x)
run_test(df_jax,x)
run_test(df2,x)
run_test(df_jax,x)

df , time: 0.0006592273712158203 , n: 100
jacfun , time: 0.007133960723876953 , n: 100
df2 , time: 0.0010800361633300781 , n: 100
jacfun , time: 0.010263919830322266 , n: 100


In [132]:
run_test(df,x,n=1000)
run_test(df_jax,x,n=1000)
run_test(df2,x,n=1000)
run_test(df_jax,x,n=1000)

df , time: 0.0007381439208984375 , n: 1000
jacfun , time: 0.010536909103393555 , n: 1000
df2 , time: 0.0012888908386230469 , n: 1000
jacfun , time: 0.007525205612182617 , n: 1000
